### ISSUE TITLE
`IndexError: pop from empty list` when calling some functions without arguments

### ISSUE THREAD

**Issue by bvanrijn** [bvanrijn/debianpaste-clients#2]
**What steps will reproduce the problem?**
(1) Call `python3 paste.py geturl` without any arguments

**What is the expected output?**
Receive a friendly error, because no URL is given

**What do you see instead?**
An error message `IndexError: pop from empty list`.

**Error:**
`IndexError: pop from empty list`

**Traceback:**

```
Traceback (most recent call last):
  File "paste.py", line 201, in <module>
    (msg, ret) = action.call(actions[cmd])
  File "paste.py", line 49, in call
    return self.__getattribute__(method_name)()
  File "paste.py", line 111, in actionGetShortUrl
    url = self.args_.pop(0)
IndexError: pop from empty list
```

**Comment by bvanrijn** [comment]
Reopening because `pop(0)` is in many more places than I thought.
At least now I know how to fix it. This should go smoothly.
