### ISSUE TITLE
`add` without pipe hangs forever

### ISSUE THREAD

**Issue by bvanrijn** [bvanrijn/debianpaste-clients#5]
**What steps will reproduce the problem?**
(1) Type `python3 paste.py add` without arguments

**What is the expected output?**
That `paste` does something instead of waiting forever for standard input

**What do you see instead?**
It seems like `paste` hangs while it waits for standard input

**Error:**
No error. But after stopping `paste` with ^C:

```
KeyboardInterrupt
```

**Traceback:**

```
Traceback (most recent call last):
  File "paste.py", line 230, in <module>
    (msg, ret) = action.call(actions[cmd])
  File "paste.py", line 56, in call
    return self.__getattribute__(method_name)()
  File "paste.py", line 69, in actionAddPaste
    code = [ i.rstrip() for i in sys.stdin.readlines() ]
KeyboardInterrupt
```

A possible way to fix this issue would be to check if a pipe is being used, and if not, use a simple text editor like `vi` or `nano`.

**Comment by bvanrijn** [comment]
Hm. I don't know. `cat` also hangs forever when called without a filename argument.
